default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432

local: &local
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DATABASE'] %>

development:
  <<: *default
  <<: *local
  database: library_system_development

test:
  <<: *default
  <<: *local
  database: library_system_test